### PR TITLE
fix(effect): migrate service access to Effect beta 66

### PR DESCRIPTION
**Pull request by notkadez**
## Summary

Updates Motel to work with `effect@4.0.0-beta.66`.

Effect beta 66 removed `Context.Service#asEffect()`. Service tags are now directly usable as Effects, so calls like:

```ts
Effect.flatMap(TraceQueryService.asEffect(), ...)
```

fail at runtime. This PR replaces those calls with the beta 66-compatible form:

```ts
Effect.flatMap(TraceQueryService, ...)
```

## Changes

- Pins all Effect packages to `4.0.0-beta.66` to prevent accidental resolution to a newer Effect beta
- Replaces `.asEffect()` service access across:
  - local server handlers
  - CLI commands
  - TUI loaders
  - tests
  - repro seed scripts
  - benchmark scripts
- Refreshes `bun.lock`

## Why

Running Motel through `bunx @kitlangton/motel` can currently crash during startup with a React/OpenTUI stack trace rooted at:

```log
TypeError: TraceQueryService.asEffect is not a function
```

`bunx` installs Motel into a fresh temporary environment, so it resolves dependencies from Motel’s published semver ranges rather than from this repository’s lockfile. Motel currently declares Effect dependencies with beta ranges such as `^4.0.0-beta.49`, which allows Bun to resolve a newer Effect beta.

In newer Effect 4 betas, `Context.Service#asEffect()` has been removed. Service tags are directly usable as Effects instead, so the older `.asEffect()` calls fail at runtime when Bun resolves Motel against the newer Effect API.

## Validation

- [x] `bun run typecheck`
- [x] `bun run test`
- [x] `bun run web:build`
- [x] Smoke-tested local server:
  - `GET /api/health`
  - `GET /api/services`
  - `GET /api/facets?type=traces&field=attribute_keys&limit=20`
- [x] Smoke-tested CLI:
  - `bun run cli services`

## Compatibility Notes

This intentionally targets Effect beta 66. The main behavioral change is a mechanical service access migration from `.asEffect()` to direct service tags.

No API routes, CLI commands, storage schema, or UI behavior are changed.

### CODE REVIEW

**Comment by nikelborm** [comment]
While Kit is busy with moving the AI frontiers at opencode, you can use this pr by `bunx @evadev/motel`

**Comment by Mark-Life** [comment]
thanks for this PR

**Comment by kitlangton** [comment]
The fresh-install Effect compatibility failure is fixed on `main` in d449ac3. The landed change migrates service access away from `.asEffect()` and updates the coordinated Effect dependency set to beta.90 rather than pinning beta.66.

Thanks for identifying the removed API and providing the migration path.

**Comment by nikelborm** [comment]
Just reread my last message. I didn't mean to sound passive-aggressive/sarcastic, but if it came across that way, I apologize. I meant literally because Kit, from what I understand, is busy. I respect open-source projects like opencode, and anyone working full-time on one inspires me greatly.

Thanks for the update, Kit!
